[build]
  publish = "."

# Redirect root to Turkish home
[[redirects]]
  from = "/"
  to = "/tr/"
  status = 301

# Custom 404 Page
[[redirects]]
  from = "/*"
  to = "/tr/404.html"
  status = 404

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"